### PR TITLE
Problem: flaky and slow Android integration test (fix #566)

### LINKED ISSUE #566: Problem: flaky and slow Android integration test
currently, the Android integration test can take over 1 hour and often fails: https://github.com/crypto-com/defi-wallet-core-rs/actions/workflows/android-build.yml

### PR DESCRIPTION
**Pull request by SHH-HaoZhang**

### CODE REVIEW

**Comment by damoncro** [comment]
> As of NDK r19, the toolchains installed by default with the NDK may be used in-place. The make_standalone_toolchain.py script is no longer needed for interfacing with arbitrary build systems. 
Please check https://developer.android.com/ndk/guides/other_build_systems

You can also refer to the android build on play-cpp-sdk:

https://github.com/cronos-labs/play-cpp-sdk/blob/main/Makefile#L96-L99
@SHH-HaoZhang

**Comment by SHH-HaoZhang** [comment]
> > As of NDK r19, the toolchains installed by default with the NDK may be used in-place. The make_standalone_toolchain.py script is no longer needed for interfacing with arbitrary build systems.
> > Please check https://developer.android.com/ndk/guides/other_build_systems
> 
> You can also refer to the android build on play-cpp-sdk:
> 
> https://github.com/cronos-labs/play-cpp-sdk/blob/main/Makefile#L96-L99 @SHH-HaoZhang

I have made related attempts, but it seems that it is not very compatible with cargo.

**Comment by damoncro** [comment]
yes, you can try to setup the following envs (any one missing will be error):

TARGET (very important, should be the same as rust target, for example, armv7-linux-androideabi)
TARGET_CC
CXX (may not necessary for defi-wallet-core)
TARGET_AR
CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER (depends on the TARGET)

**Comment by damoncro** [comment]
I successfully build android builds for play-cpp-sdk. You can check https://github.com/cronos-labs/play-cpp-sdk/blob/main/Makefile.

**Review by tomtau — APPROVED** [review]

**Pull request merged**
