### PR TITLE
Problem: missing support for CMake (fix #265)

### LINKED ISSUE #265: Problem: missing support for CMake
add  CMake build system for cross platform
-windows
-mac
-freebsd

### PR DESCRIPTION
**Pull request by damoncro**
Solution:
- Add basic cmake support and test cmake in CI
- Move the libraries and bindings to sdk
- Integrate x86_64 and amd64 in Makefile
- Add linux_build.yml
- Use rpath for mac dynamic library
- Use so file for linux dynamic library
- Simplify the process of build example by one `make`

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [x] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CONTRIBUTING.md)?
- [x] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [x] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles? (`cargo build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`cargo test`)
- [ ] Have you checked your code formatting is correct? (`cargo fmt -- --check --color=auto`)
- [ ] Have you checked your basic code style is fine? (`cargo clippy`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`cargo audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by damoncro** [comment]
I am still working on cmake in windows.

**Review by tomtau — COMMENTED** [review]
should that helper.py be removed if this is now done via cmake?

**Comment by damoncro** [comment]
It is difficult at this moment, helper.py carries some string replacement works...

**Comment by damoncro** [comment]
Follow up issue: https://github.com/crypto-com/defi-wallet-core-rs/issues/462

**Comment by tomtau** [comment]
btw https://stackoverflow.com/questions/62648369/best-way-to-call-cargo-from-cmake

**Comment by tomtau** [comment]
https://github.com/corrosion-rs/corrosion

**Review by tomtau — APPROVED** [review]
not a cmake expert, so not sure if this follows all the modern idioms: https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1 https://cliutils.gitlab.io/modern-cmake/ but I guess it could be potentially improved in follow up PRs

**Comment by damoncro** [comment]
Cool references, I will check and improve in another PR.

**Pull request merged**
