### PR TITLE
Problem: error is generated if set_ethers_httpagent called after get_ethers_provider fix (#676)

### PR DESCRIPTION
**Pull request by damoncro**
Close:
- #676

Solution:
- Only get `G_AGENTINFO` in get_ethers_provider

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles? (`cargo build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`cargo test`)
- [ ] Have you checked your code formatting is correct? (`cargo fmt -- --check --color=auto`)
- [ ] Have you checked your basic code style is fine? (`cargo clippy`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`cargo audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/defi-wallet-core-rs/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
is this desired? the described "problem" seems to be a feature, i.e. user agent should be set just once during the initialisation: https://github.com/crypto-com/defi-wallet-core-rs/pull/519#pullrequestreview-1050532706 ?

but if it's needed to be set it afterwards or multiple times / to multiple values, it's ok to have a mutex?

One alternative is still to have Once, but not automatically set in `get_ethers_provider`: i.e. just use `get` (instead of `get_or_init`) and either return an error (that it should be initialised with `set_ethers_httpagent`) or just do `unwrap_or_else` on the option returned by `get` (i.e. `G_AGENTINFO` will remain not initialised / can be initialized later, but the user agent will be set to some default value)

**Comment by damoncro** [comment]
It is difficult to manage: `user agent should be set just once during the initialisation`.  
I found that,
1. In unreal, the Actor Constructor is called multiple times in compile time, which make the package failed.
2. If the Actor: BP_Cronos has two or more instances, it is also impossible to just called once.
3. It is exposed as a function, it has the change to be called multiple times unless we hardcode it.

**Comment by tomtau** [comment]
@damoncro how about calling it in `Init` of `UGameInstance` (only once in the program startup): https://docs.unrealengine.com/5.0/en-US/API/Runtime/Engine/Engine/UGameInstance/Init/ ?

**Comment by damoncro** [comment]
@tomtau it is modify the game instance in the game itself, instead of plugin, right?

**Comment by damoncro** [comment]
> One alternative is still to have Once, but not automatically set in get_ethers_provider: i.e. just use get (instead of get_or_init) and either return an error (that it should be initialised with set_ethers_httpagent) or just do unwrap_or_else on the option returned by get (i.e. G_AGENTINFO will remain not initialised / can be initialized later, but the user agent will be set to some default value)
Yup, it is an alternative way. We do not set default useragent in `get_ethers_provider`, only get inside. And `set_ethers_httpagent` could be called multiple times, first time will be set, any calls after that will return error but we just ignore it.

**Comment by damoncro** [comment]
Done~
@tomtau @leejw51crypto

**Review by tomtau — APPROVED** [review]

**Pull request merged**
